Add TTS Wavenet
rhasspy/rhasspy pull request #73
Opened 2020-06-20 13:57 UTC by Romkabouter

I have the TTS Wavenet added as a submodule on my own github url, I think it should be moved to rhasspy/rhasspy-tts-wavenet-hermes but I do not now how.
Please advise

2020-06-20 17:05 UTC, maxbachmann commented
I added it here: https://github.com/rhasspy/rhasspy-tts-wavenet-hermes

2020-06-21 20:50 UTC, Romkabouter commented
I can fix this test (I did a small test on a ubuntu vm), however I do not know what "deploy" target should do. Can anyone explain this?

2020-06-22 07:00 UTC, koenvervloesem commented
This should build the Docker image and optionally push it to Docker Hub. You can see this in the Makefile of some of the other repositories. But @synesthesiam is in the process of rewriting the Makefile logic, I'll ask him to review what should happen here.

2020-06-28 20:34 UTC, maxbachmann requested changes
@Romkabouter 
1) The submodule should be updated to point to https://github.com/rhasspy/rhasspy-tts-wavenet-hermes
2) It appears to me that you pushed `rhasspywake_pocketsphinx_hermes` instead of the google wavenet code by mistake. https://github.com/rhasspy/rhasspy-tts-wavenet-hermes/tree/master/rhasspywake_pocketsphinx_hermes

2020-07-02 17:55 UTC, Romkabouter commented
I am closing this PR and made a new one on rhasspy/rhasspy-tts-wavenet-hermes with the correct code.
That way the submodule is already ok.

2020-07-02 17:55 UTC, closed without merging